### ISSUE TITLE
Cannot build AgreementMaker

### ISSUE THREAD

**Issue by Ellen625** [agreementmaker/agreementmaker#39]
I have got this error, when built with ./mvnw install -DskipTests=true

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project AgreementMaker-AlignmentRepair: Compilation failure
[ERROR] /Users/ellen/eclipse-workspace/agreementmaker/AgreementMaker-OSGi/AgreementMaker-AlignmentRepair/src/main/java/am/evaluation/repair/HermitReasonerTest.java:[14,35] package jdk.internal.jline.internal does not exist

My java version is "1.8.0_171"

**Comment by cstroe** [comment]
@Ellen625 Did this fix your build?

**Comment by cstroe** [comment]
This PR fixed the build: https://github.com/agreementmaker/agreementmaker/pull/41/files

**Comment by eliohb** [comment]
hello how can i run the am.ui.glue.StartAgreementMaker class from the command line

**Comment by eliohb** [comment]
@cstroe  i have the command line mvnw install -DskipTests=true in the agreementmaker-osgi and it worked .How can i run the am.ui.glue.StartAgreementMaker class from the command line
thank u

**Comment by cstroe** [comment]
@eliohb, the way to run the application now is using Gradle: `./gradlew run`
