### ISSUE TITLE
running isuue

### ISSUE THREAD

**Issue by eliohb** [agreementmaker/agreementmaker#42]
When i try to run th egreementmaker by applying the following command:
./mvnw pax:provision

i am getting the following error:
Found "C:\Users\hbeich\Desktop\agreementmaker-master\AgreementMaker-OSGi\.mvn\wr
apper\maven-wrapper.jar"
[INFO] Scanning for projects...
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Build Order:
[INFO]
[INFO] AgreementMaker-OSGi                                                [pom]
[INFO] AgreementMaker API                                                 [jar]
[INFO] AgreementMaker WordNet                                             [jar]
[INFO] AgreementMaker Similarity Metrics                                  [jar]
[INFO] AgreementMaker-Core                                                [jar]
[INFO] AgreementMaker GeoNames                                            [jar]
[INFO] Matcher-BaseSimilarity                                             [jar]
[INFO] AgreementMaker-Matchers                                            [jar]
[INFO] Matcher-AdvancedSimilarity                                         [jar]
[INFO] Matcher-PRA                                                        [jar]
[INFO] Matcher-OAEI                                                       [jar]
[INFO] AgreementMaker-UI                                                  [jar]
[INFO] Matcher-LinkedOpenData                                             [jar]
[INFO] AgreementMaker-BatchMode                                           [jar]
[INFO] AgreementMaker-CollaborationClient                                 [jar]
[INFO] AgreementMaker-UserFeedback                                        [jar]
[INFO] AgreementMaker-SemanticExplanation                                 [jar]
[INFO] Matcher-IMEI2013                                                   [jar]
[INFO] AgreementMaker-MatcherRegistry                                     [jar]
[INFO] AgreementMaker-UIGlue                                              [jar]
[INFO] AgreementMaker-AlignmentRepair                                     [jar]
Downloading from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo
/maven-metadata.xml
Downloading from central: https://repo.maven.apache.org/maven2/org/apache/maven/
plugins/maven-metadata.xml
Downloaded from central: https://repo.maven.apache.org/maven2/org/apache/maven/p
lugins/maven-metadata.xml (14 kB at 24 kB/s)
Downloaded from central: https://repo.maven.apache.org/maven2/org/codehaus/mojo/
maven-metadata.xml (20 kB at 36 kB/s)
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] AgreementMaker-OSGi 0.3.0-SNAPSHOT ................. SKIPPED
[INFO] AgreementMaker API 0.0.1-SNAPSHOT .................. SKIPPED
[INFO] AgreementMaker WordNet 0.0.1-SNAPSHOT .............. SKIPPED
[INFO] AgreementMaker Similarity Metrics 0.0.1-SNAPSHOT ... SKIPPED
[INFO] AgreementMaker-Core ................................ SKIPPED
[INFO] AgreementMaker GeoNames 0.0.1-SNAPSHOT ............. SKIPPED
[INFO] Matcher-BaseSimilarity 1.0.0-SNAPSHOT .............. SKIPPED
[INFO] AgreementMaker-Matchers 1.0.0-SNAPSHOT ............. SKIPPED
[INFO] Matcher-AdvancedSimilarity 1.0.0-SNAPSHOT .......... SKIPPED
[INFO] Matcher-PRA 1.0.0-SNAPSHOT ......................... SKIPPED
[INFO] Matcher-OAEI 1.0.0-SNAPSHOT ........................ SKIPPED
[INFO] AgreementMaker-UI 1.0.0-SNAPSHOT ................... SKIPPED
[INFO] Matcher-LinkedOpenData 1.0.0-SNAPSHOT .............. SKIPPED
[INFO] AgreementMaker-BatchMode 1.0.0-SNAPSHOT ............ SKIPPED
[INFO] AgreementMaker-CollaborationClient 1.0.0-SNAPSHOT .. SKIPPED
[INFO] AgreementMaker-UserFeedback 1.0.0-SNAPSHOT ......... SKIPPED
[INFO] AgreementMaker-SemanticExplanation 1.0.0-SNAPSHOT .. SKIPPED
[INFO] Matcher-IMEI2013 1.0.0-SNAPSHOT .................... SKIPPED
[INFO] AgreementMaker-MatcherRegistry 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] AgreementMaker-UIGlue 1.0.0-SNAPSHOT ............... SKIPPED
[INFO] AgreementMaker-AlignmentRepair 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.654 s
[INFO] Finished at: 2019-03-01T10:06:26+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'pax' in the current project and in the plugi
n groups [org.apache.maven.plugins, org.codehaus.mojo] available from the reposi
tories [local (C:\Users\hbeich\.m2\repository), central (https://repo.maven.apac
he.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundF
orPrefixException

Any advice

**Comment by cstroe** [comment]
I'll look into this, it seems we haven't published the external jars.

**Comment by cstroe** [comment]
I see the following, which leads me to think that I need to publish the JAWS dependency:
```
[ERROR] Failed to execute goal on project AgreementMaker-WordNet: Could not resolve dependencies for project edu.uic.cs.advis.am:AgreementMaker-WordNet:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.github.agreementmaker:jaws:jar:1.3: Failed to read artifact descriptor for com.github.agreementmaker:jaws:jar:1.3: Could not transfer artifact com.github.agreementmaker:jaws:pom:1.3 from/to Maven Repo (http://onawh.im/maven): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

**Comment by EngyNasr** [comment]
I have the same exact issue, when trying to run mvnw.cmd clean install

Failed to execute goal on project AgreementMaker-WordNet: Could not resolve dependencies for project edu.uic.cs.advis.am:AgreementMaker-WordNet:jar:0.0.1-SNAPSHOT: Failed to collect dependencies at com.github.agreementmaker:jaws:jar:1.3: Failed to read artifact descriptor for com.github.agreementmaker:jaws:jar:1.3: Could not transfer artifact com.github.agreementmaker:jaws:pom:1.3 from/to Maven Repo (http://onawh.im/maven): onawh.im:443 failed to respond 


Do you have a solution for that ?

Thanks in advance :)

**Comment by cstroe** [comment]
@EngyNasr yes, I've updated the URL to be correct: https://github.com/agreementmaker/agreementmaker/commit/4ff90636d64e8ae48854367f6f3c27aa148508eb

Please try again.

**Comment by EngyNasr** [comment]
@cstroe Thank you so much that's really helped a lot :) 
It passed the WordNet failure finally, but currently it gives a failure in BatchMode

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project AgreementMaker-BatchMode: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Nasr\Desktop\For Setup\agreementmaker-master\agreementmaker-master\AgreementMaker-OSGi\AgreementMaker-BatchMode\target\surefire-reports for the individual test results.

Thanks a lot for your great help

**Comment by EngyNasr** [comment]
@cstroe Its solved, thanks a lot ;)

**Comment by EngyNasr** [comment]
@cstroe One last step, when I am trying to start Agreementmaker by ./mvnw pax:provision, I got this error

No plugin found for prefix 'pax' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Nasr\.m2\repository), central (https://repo.maven.apache.org/maven2)] 

Thanks again :)

**Comment by cstroe** [comment]
@EngyNasr I switched the build to use Gradle.  Please update from master and use the command `./gradlew run`.
