### ISSUE TITLE
Surefire error

### ISSUE THREAD

**Issue by onetarik** [agreementmaker/agreementmaker#43]
I have the following error when i try to build using mvnw install

[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project AgreementMaker-BatchMode: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\User\git\agreementmaker1\AgreementMaker-OSGi\AgreementMaker-BatchMode\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :AgreementMaker-BatchMode

Thank you

**Comment by cstroe** [comment]
@onetarik please rerun the build with `mvn install -DskipTests` ... we will work on fixing the tests.

**Comment by onetarik** [comment]
Thank you very much 
yes that's what i did finally

**Comment by cstroe** [comment]
For reference, we now support a Gradle build: `./gradle run` from the root of the project to run AgreementMaker.
