### ISSUE TITLE
Pax Plugin issue 

### ISSUE THREAD

**Issue by EngyNasr** [agreementmaker/agreementmaker#44]
When trying to run Agreementmaker by mvnw pax:provision, I got the following, I have tried adding the plugin in the pom.xml file but got other errors such as org.ops4j.pax.runner.platform.PlatformException: Execution environment [J2SE-12.] could not be found

Kindly please help, thanks a lot in advance :) 

[ERROR] No plugin found for prefix 'pax' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (C:\Users\Nasr\.m2\repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by 869277160** [comment]
I got this too!!!!  
I typed the command    mvnw pax:provision   on my Windows console，and the result is like the picture below. 
![5655O`{{A8WE(2~EJJ9V`BT](https://user-images.githubusercontent.com/14818076/61341039-658fac80-a877-11e9-8268-a1cf99223722.png)

**Comment by cstroe** [comment]
I gave up on Pax and the Pax plugin.  Please use the Grade build now, "./gradlew run" from the root of the project.
