### ISSUE TITLE
Document batch mode

### ISSUE THREAD

**Issue by cstroe** [agreementmaker/agreementmaker#8]
AgreementMaker has a batch mode module.  You can use it to define your matching tasks in an XML file, and then run them all automatically at once, without the GUI.

I will write some documentation around it.

**Comment by cstroe** [comment]
Currently the batch mode be used to specify one or more "ontology matching tasks".  A matching task is currently defined as:
* a source ontology (OWL)
* a target ontology (OWL)
* and output alignment file (OAEI/RDF format)

The batch mode runner will load the source and target ontology and instantiate the OAEI2011Matcher and match the two ontologies.

This is a very basic and inflexible approach to the batch mode, and should be improved.

**Comment by cstroe** [comment]
Batch mode has been reworked to work with JSON files and documented in the wiki.  Tested the limited functionality that the Batch Mode runner has.

Missing features:
* Ability to pass parameters to the matcher or selector.

**Comment by eliohb** [comment]
Hello i am trying to use the agreementmaker but when i use the command line mvn install the following 
error appears any suggestion:
AgreementMaker-OSGi 0.3.0-SNAPSHOT ................. SUCCESS [  0.987 s]
[INFO] AgreementMaker API 0.0.1-SNAPSHOT .................. SUCCESS [  1.994 s]
[INFO] AgreementMaker WordNet 0.0.1-SNAPSHOT .............. SUCCESS [  0.445 s]
[INFO] AgreementMaker Similarity Metrics 0.0.1-SNAPSHOT ... SUCCESS [  1.811 s]
[INFO] AgreementMaker-Core 0.3.0-SNAPSHOT ................. SUCCESS [ 21.700 s]
[INFO] AgreementMaker GeoNames 0.0.1-SNAPSHOT ............. SUCCESS [  0.240 s]
[INFO] Matcher-BaseSimilarity 1.0.0-SNAPSHOT .............. SUCCESS [  0.232 s]
[INFO] AgreementMaker-Matchers 1.0.0-SNAPSHOT ............. SUCCESS [  2.336 s]
[INFO] Matcher-AdvancedSimilarity 1.0.0-SNAPSHOT .......... SUCCESS [  0.188 s]
[INFO] Matcher-PRA 1.0.0-SNAPSHOT ......................... SUCCESS [  0.177 s]
[INFO] Matcher-OAEI 1.0.0-SNAPSHOT ........................ SUCCESS [  1.782 s]
[INFO] AgreementMaker-UI 1.0.0-SNAPSHOT ................... SUCCESS [  5.126 s]
[INFO] Matcher-LinkedOpenData 1.0.0-SNAPSHOT .............. SUCCESS [  2.788 s]
[INFO] AgreementMaker-BatchMode 1.0.0-SNAPSHOT ............ FAILURE [  3.661 s]
[INFO] AgreementMaker-CollaborationClient 1.0.0-SNAPSHOT .. SKIPPED
[INFO] AgreementMaker-UserFeedback 1.0.0-SNAPSHOT ......... SKIPPED
[INFO] AgreementMaker-SemanticExplanation 1.0.0-SNAPSHOT .. SKIPPED
[INFO] Matcher-IMEI2013 1.0.0-SNAPSHOT .................... SKIPPED
[INFO] AgreementMaker-MatcherRegistry 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] AgreementMaker-UIGlue 1.0.0-SNAPSHOT ............... SKIPPED
[INFO] AgreementMaker-AlignmentRepair 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  43.879 s
[INFO] Finished at: 2019-02-25T21:50:45+02:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project AgreementMaker-BatchMode: There are test failures.
[ERROR]
[ERROR] Please refer to C:\Users\Toshiba\Desktop\agreementmaker-master\AgreementMaker-OSGi\AgreementMaker-BatchMode\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :AgreementMaker-BatchMode.

thank u

**Comment by cstroe** [comment]
@eliohb I ran the following commands:
```
cd AgreementMaker-OSGi
./mvnw clean install
```

Got the following:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] AgreementMaker-OSGi 0.3.0-SNAPSHOT ................. SUCCESS [  1.231 s]
[INFO] AgreementMaker API 0.0.1-SNAPSHOT .................. SUCCESS [  1.949 s]
[INFO] AgreementMaker WordNet 0.0.1-SNAPSHOT .............. SUCCESS [  0.316 s]
[INFO] AgreementMaker Similarity Metrics 0.0.1-SNAPSHOT ... SUCCESS [  7.059 s]
[INFO] AgreementMaker-Core ................................ SUCCESS [ 17.075 s]
[INFO] AgreementMaker GeoNames 0.0.1-SNAPSHOT ............. SUCCESS [  0.174 s]
[INFO] Matcher-BaseSimilarity 1.0.0-SNAPSHOT .............. SUCCESS [  0.302 s]
[INFO] AgreementMaker-Matchers 1.0.0-SNAPSHOT ............. SUCCESS [  4.489 s]
[INFO] Matcher-AdvancedSimilarity 1.0.0-SNAPSHOT .......... SUCCESS [  0.257 s]
[INFO] Matcher-PRA 1.0.0-SNAPSHOT ......................... SUCCESS [  0.373 s]
[INFO] Matcher-OAEI 1.0.0-SNAPSHOT ........................ SUCCESS [  1.741 s]
[INFO] AgreementMaker-UI 1.0.0-SNAPSHOT ................... SUCCESS [  2.449 s]
[INFO] Matcher-LinkedOpenData 1.0.0-SNAPSHOT .............. SUCCESS [  0.794 s]
[INFO] AgreementMaker-BatchMode 1.0.0-SNAPSHOT ............ SUCCESS [  4.016 s]
[INFO] AgreementMaker-CollaborationClient 1.0.0-SNAPSHOT .. SUCCESS [  0.386 s]
[INFO] AgreementMaker-UserFeedback 1.0.0-SNAPSHOT ......... SUCCESS [  5.116 s]
[INFO] AgreementMaker-SemanticExplanation 1.0.0-SNAPSHOT .. SUCCESS [  0.051 s]
[INFO] Matcher-IMEI2013 1.0.0-SNAPSHOT .................... SUCCESS [  0.248 s]
[INFO] AgreementMaker-MatcherRegistry 0.0.1-SNAPSHOT ...... SUCCESS [  0.185 s]
[INFO] AgreementMaker-UIGlue 1.0.0-SNAPSHOT ............... SUCCESS [  0.281 s]
[INFO] AgreementMaker-AlignmentRepair 0.0.1-SNAPSHOT ...... SUCCESS [  0.509 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 49.347 s
[INFO] Finished at: 2019-02-27T22:17:55-06:00
[INFO] ------------------------------------------------------------------------
```

Can you open a new issue on GitHub with more details?

**Comment by eliohb** [comment]
@cstroe i ran the following commands:
C:\Users\hbeich>cd desktop/agreement

C:\Users\hbeich\Desktop\agreement>cd agreementmarket-osgi
Le chemin d'accès spécifié est introuvable.

C:\Users\hbeich\Desktop\agreement>cd AgreementMaker-OSGi

C:\Users\hbeich\Desktop\agreement\AgreementMaker-OSGi>./mvnw clean install
'.' n'est pas reconnu en tant que commande interne
ou externe, un programme exécutable ou un fichier de commandes.

C:\Users\hbeich\Desktop\agreement\AgreementMaker-OSGi> mvnw.cmd clean install
the below result appearswith the error:

[INFO]
[INFO] --- jacoco-maven-plugin:0.8.2:prepare-agent (prepare-agent) @ AgreementMa
ker-BatchMode ---
[INFO] argLine set to -javaagent:C:\\Users\\hbeich\\.m2\\repository\\org\\jacoco
\\org.jacoco.agent\\0.8.2\\org.jacoco.agent-0.8.2-runtime.jar=destfile=C:\\Users
\\hbeich\\Desktop\\agreementmaker\\AgreementMaker-OSGi\\AgreementMaker-BatchMode
\\target\\jacoco.exec
[INFO]
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ AgreementM
aker-BatchMode ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 2 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:compile (default-compile) @ AgreementMake
r-BatchMode ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 34 source files to C:\Users\hbeich\Desktop\agreementmaker\Agree
mentMaker-OSGi\AgreementMaker-BatchMode\target\classes
[INFO] /C:/Users/hbeich/Desktop/agreementmaker/AgreementMaker-OSGi/AgreementMake
r-BatchMode/src/main/java/am/extension/batchmode/conflictResolution/ConflictsRes
olution.java: Some input files use or override a deprecated API.
[INFO] /C:/Users/hbeich/Desktop/agreementmaker/AgreementMaker-OSGi/AgreementMake
r-BatchMode/src/main/java/am/extension/batchmode/conflictResolution/ConflictsRes
olution.java: Recompile with -Xlint:deprecation for details.
[INFO]
[INFO] --- maven-resources-plugin:2.6:testResources (default-testResources) @ Ag
reementMaker-BatchMode ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 4 resources
[INFO]
[INFO] --- maven-compiler-plugin:3.8.0:testCompile (default-testCompile) @ Agree
mentMaker-BatchMode ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 5 source files to C:\Users\hbeich\Desktop\agreementmaker\Agreem
entMaker-OSGi\AgreementMaker-BatchMode\target\test-classes
[INFO] /C:/Users/hbeich/Desktop/agreementmaker/AgreementMaker-OSGi/AgreementMake
r-BatchMode/src/test/java/am/extension/batchmode/simpleBatchMode/SimpleBatchMode
RunnerTest.java: C:\Users\hbeich\Desktop\agreementmaker\AgreementMaker-OSGi\Agre
ementMaker-BatchMode\src\test\java\am\extension\batchmode\simpleBatchMode\Simple
BatchModeRunnerTest.java uses unchecked or unsafe operations.
[INFO] /C:/Users/hbeich/Desktop/agreementmaker/AgreementMaker-OSGi/AgreementMake
r-BatchMode/src/test/java/am/extension/batchmode/simpleBatchMode/SimpleBatchMode
RunnerTest.java: Recompile with -Xlint:unchecked for details.
[INFO]
[INFO] --- maven-surefire-plugin:2.19.1:test (default-test) @ AgreementMaker-Bat
chMode ---

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running am.extension.batchmode.internal.BatchModeFileReaderImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.889 sec - in a
m.extension.batchmode.internal.BatchModeFileReaderImplTest
Running am.extension.batchmode.internal.BatchModeFileWriterImplTest
Tests run: 2, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.094 sec <<< FA
ILURE! - in am.extension.batchmode.internal.BatchModeFileWriterImplTest
test_two_task_output(am.extension.batchmode.internal.BatchModeFileWriterImplTest
)  Time elapsed: 0.094 sec  <<< FAILURE!
junit.framework.ComparisonFailure:
Streams differ. expected:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/alignment1.rdf"
    }
  }, {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file3.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher2"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector3"
    },
    "output" : {
      "filePath" : "/path/some/alignment2.rdf"
    }
  } ]]
}> but was:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/alignment1.rdf"
    }
  }, {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file3.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher2"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector3"
    },
    "output" : {
      "filePath" : "/path/some/alignment2.rdf"
    }
] } ]
}>
        at am.extension.batchmode.internal.BatchModeFileWriterImplTest.test_two_
task_output(BatchModeFileWriterImplTest.java:64)

test_simple_output(am.extension.batchmode.internal.BatchModeFileWriterImplTest)
 Time elapsed: 0 sec  <<< FAILURE!
junit.framework.ComparisonFailure:
Streams differ. expected:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/file.rdf"
    }
  } ]]
}> but was:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/file.rdf"
    }
] } ]
}>
        at am.extension.batchmode.internal.BatchModeFileWriterImplTest.test_simp
le_output(BatchModeFileWriterImplTest.java:34)

Running am.extension.batchmode.internal.BatchModeSpecImplTest
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0 sec - in am.ex
tension.batchmode.internal.BatchModeSpecImplTest
Running am.extension.batchmode.simpleBatchMode.SimpleBatchModeRunnerTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.624 sec - in a
m.extension.batchmode.simpleBatchMode.SimpleBatchModeRunnerTest

Results :

Failed tests:
  BatchModeFileWriterImplTest.test_simple_output:34 Streams differ. expected:<{[

  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/file.rdf"
    }
  } ]]
}> but was:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/file.rdf"
    }
] } ]
}>
  BatchModeFileWriterImplTest.test_two_task_output:64 Streams differ. expected:<
{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/alignment1.rdf"
    }
  }, {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file3.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher2"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector3"
    },
    "output" : {
      "filePath" : "/path/some/alignment2.rdf"
    }
  } ]]
}> but was:<{[
  "tasks" : [ {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file2.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector"
    },
    "output" : {
      "filePath" : "/path/some/alignment1.rdf"
    }
  }, {
    "sourceOntology" : "/path/to/some/file1.owl",
    "targetOntology" : "/path/to/some/file3.owl",
    "matcher" : {
      "canonicalClassName" : "com.some.package.Matcher2"
    },
    "selector" : {
      "canonicalClassName" : "com.some.package.Selector3"
    },
    "output" : {
      "filePath" : "/path/some/alignment2.rdf"
    }
] } ]
}>

Tests run: 7, Failures: 2, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] AgreementMaker-OSGi 0.3.0-SNAPSHOT ................. SUCCESS [  2.217 s]
[INFO] AgreementMaker API 0.0.1-SNAPSHOT .................. SUCCESS [  3.919 s]
[INFO] AgreementMaker WordNet 0.0.1-SNAPSHOT .............. SUCCESS [  0.453 s]
[INFO] AgreementMaker Similarity Metrics 0.0.1-SNAPSHOT ... SUCCESS [  3.300 s]
[INFO] AgreementMaker-Core ................................ SUCCESS [ 21.445 s]
[INFO] AgreementMaker GeoNames 0.0.1-SNAPSHOT ............. SUCCESS [  0.343 s]
[INFO] Matcher-BaseSimilarity 1.0.0-SNAPSHOT .............. SUCCESS [  0.640 s]
[INFO] AgreementMaker-Matchers 1.0.0-SNAPSHOT ............. SUCCESS [  5.263 s]
[INFO] Matcher-AdvancedSimilarity 1.0.0-SNAPSHOT .......... SUCCESS [  0.406 s]
[INFO] Matcher-PRA 1.0.0-SNAPSHOT ......................... SUCCESS [  0.454 s]
[INFO] Matcher-OAEI 1.0.0-SNAPSHOT ........................ SUCCESS [  2.422 s]
[INFO] AgreementMaker-UI 1.0.0-SNAPSHOT ................... SUCCESS [  4.087 s]
[INFO] Matcher-LinkedOpenData 1.0.0-SNAPSHOT .............. SUCCESS [  1.806 s]
[INFO] AgreementMaker-BatchMode 1.0.0-SNAPSHOT ............ FAILURE [  4.632 s]
[INFO] AgreementMaker-CollaborationClient 1.0.0-SNAPSHOT .. SKIPPED
[INFO] AgreementMaker-UserFeedback 1.0.0-SNAPSHOT ......... SKIPPED
[INFO] AgreementMaker-SemanticExplanation 1.0.0-SNAPSHOT .. SKIPPED
[INFO] Matcher-IMEI2013 1.0.0-SNAPSHOT .................... SKIPPED
[INFO] AgreementMaker-MatcherRegistry 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] AgreementMaker-UIGlue 1.0.0-SNAPSHOT ............... SKIPPED
[INFO] AgreementMaker-AlignmentRepair 0.0.1-SNAPSHOT ...... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 51.699 s
[INFO] Finished at: 2019-02-28T09:03:18+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
19.1:test (default-test) on project AgreementMaker-BatchMode: There are test fai
lures.
[ERROR]
[ERROR] Please refer to C:\Users\hbeich\Desktop\agreementmaker\AgreementMaker-OS
Gi\AgreementMaker-BatchMode\target\surefire-reports for the individual test resu
lts.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the commands:
[ERROR]   mvn <goals> -rf :AgreementMaker-BatchMode
